### ISSUE TITLE
Adding a custom handler or using isolated block editor

### ISSUE THREAD

**Issue by marcusig** [Automattic/gutenberg-everywhere#138]
Hi there, 

I'm trying to figure out if I can create a custom handler for dynamically generated textareas in the admin. 

### Context: 

I have a plugin which opens a modal in the WooCommerce product edit screen.
I would like to add an editor to textareas in that modal. 

### Issue

I did a quick test based on the Comments handler, but that added an editor to the product description textarea, and broke the rest of the product page. 

So I'm wondering if using this plugin and extending the functionality is the right approach, or if I should use the isolated block editor instead. 

And for the later, I haven't quite understood how to implement it. 
Being able to use the methods `wp.attachEditor` and `wp.detachEditor` (from https://github.com/Automattic/isolated-block-editor/blob/cb85bcfa784277197369408182995bd73670aba6/src/browser/index.js) would be perfect, but I'm not sure how to compile the minimum amount of code out of that.

Any pointers would be greatly appreciated. 

Marc

**Comment by johngodley** [comment]
Without more specifics it's hard to say what the problem is or what is the best thing to use.

This plugin is for putting Gutenberg into specific static areas of WordPress, bbPress, and BuddyPress. Although it has a system of 'handlers' it's not really a plugin to be extended by other plugins (unless it is destined to be part of this plugin).

If another plugin wants to use Gutenberg then they should use the Isolated Block Editor directly and have full control over when and how it appears. This repo can be used as an example of how to do that.

I'm not sure what you mean about compiling the minimum amount of code? Unless you need to use the static loading of Gutenberg from browser/index.js then you should look at https://github.com/Automattic/blocks-everywhere/blob/trunk/src/index.tsx as reference.

**Comment by marcusig** [comment]
Thanks John. 
I'll try using the Isolated Block Editor directly.
