### ISSUE TITLE
Add block support to bbPress emails

### ISSUE THREAD

**Issue by johngodley** [Automattic/gutenberg-everywhere#40]
bbPress sends email notifications out, and these will need to support block content.

**Comment by lamosty** [comment]
The redesigned notification emails on WP.com support forums support block content. However, in bbPress core, there's a heavy HTML stripping with `strip_tags`. Basically, core bbPress emails are text only. We don't have that in the redesigned notifications emails. However, not sure what is the best course of action for bbPress core here. Push the fully redesigned notification emails to core? Probably, so that the blocks look good in the emails. But community might not like that. Or just remove the `strip_tags` call?

If we are going with the plugin approach for Gutenberg in bbPress core, I suppose we could add the redesigned emails there, too. However, we use a lot of internal WP.com HTML emails template building functionality so not sure how portable that is.

cc @lezama

**Comment by lezama** [comment]
> If we are going with the plugin approach for Gutenberg in bbPress core, I suppose we could add the redesigned emails there, too. However, we use a lot of internal WP.com HTML emails template building functionality so not sure how portable that is.

I think we should do this and add filters to separate WPCOM only logic.

**Comment by dd32** [comment]
I would personally suggest taking the almost do-nothing approach for bbPress emails.

Ensure that the plain-text generated is good-enough, while not going above-and-beyond.

That could just mean stripping Block HTML out before bbPress strips it, so bbPress gets a "clean" text, and potentially doing some nice things like decoding code blocks and adding bullet points for lists.

**Comment by johngodley** [comment]
I've gone for a simple plain text version in #46 which replaces the content in the email with a nicer plain text version.

**Comment by johngodley** [comment]
Closing this as done.
